In [5]:
! pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.0.9-py2.py3-none-any.whl (242 kB)
Collecting et-xmlfile
  Downloading et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-1.1.0 openpyxl-3.0.9

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
price_df = pd.read_csv('data_files/수정주가.csv', encoding='euckr').head()

,코드명,A000010,A000020,A000030,A000040,A000050,A000060,A000070,A000080,A000090,...,A900340,A950010,A950030,A950070,A950100,A950110,A950130,A950140,A950160,A950170
0,종목명,조흥은행,동화약품,우리은행,KR모터스,경방,메리츠화재,삼양홀딩스,하이트진로,두산상사,...,윙입푸드,평산차업,네프로아이티,중국고섬,SBI모기지,SBI핀테크솔루션즈,엑세스바이오,잉글우드랩,코오롱티슈진(Reg.S),JTC
1,20060131,NaN,3430,NaN,2317,12164,5788,57432,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20060228,NaN,3440,NaN,2279,9693,5015,55082,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20060331,NaN,3080,NaN,2039,10187,4775,58556,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20060428,NaN,5040,NaN,1918,10985,6060,62133,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [84]:
raw_df = pd.read_excel('data_files/재무데이터 수정.xlsx')

In [85]:
raw_df.T

,0,1,2,3,4,5,6,7,8,9,...,2044,2045,2046,2047,2048,2049,2050,2051,2052,2053
Symbol,NaN,A005930,A000660,A068270,A207940,A005380,A005490,A051910,A035420,A028260,...,A303030,A267320,A271740,A257730,A232330,A297570,A279410,A258790,A264290,A010400
Symbol Name,NaN,삼성전자,SK하이닉스,셀트리온,삼성바이오로직스,현대차,POSCO,LG화학,NAVER,삼성물산,...,대신밸런스제5호스팩,교보7호스팩,한국제5호스팩,신한제3호스팩,SK3호스팩,IBKS제9호스팩,한화에이스스팩4호,케이비제11호스팩,한화에이스스팩3호,우진아이엔에스
ROA,08/4Q,7.62,0,2.92,0,4.5,12.01,12.47,36.21,0.44,...,0,0,0,0,0,0,0,0,0,0
ROA.1,09/1Q,5.24,0,4.89,0,3.94,10.04,12.54,34.97,0,...,0,0,0,0,0,0,0,0,0,0
ROA.2,09/2Q,3.78,0,8.63,0,4.67,7.16,12.97,34.45,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DPS.34,17/2Q,850,1000,19.61,0,4000,8000,6000,289.2,2000,...,0,0,0,0,0,0,0,0,0,0
DPS.35,17/3Q,850,1000,19.61,0,4000,8000,6000,289.2,2000,...,0,0,0,0,0,0,0,0,0,0
DPS.36,17/4Q,850,1000,19.61,0,4000,8000,6000,289.2,2000,...,0,0,0,0,0,0,0,0,0,0
DPS.37,18/1Q,850,1000,19.61,0,4000,8000,6000,289.2,2000,...,0,0,0,0,0,0,0,0,0,0
DPS.38,18/2Q,850,1000,19.61,0,4000,8000,6000,289.2,2000,...,0,0,0,0,0,0,0,0,0,0

In [86]:
raw_df.columns

Index(['Symbol', 'Symbol Name', 'ROA', 'ROA.1', 'ROA.2', 'ROA.3', 'ROA.4',
       'ROA.5', 'ROA.6', 'ROA.7',
       ...
       'DPS.29', 'DPS.30', 'DPS.31', 'DPS.32', 'DPS.33', 'DPS.34', 'DPS.35',
       'DPS.36', 'DPS.37', 'DPS.38'],
      dtype='object', length=651)

In [87]:
big_col = list(raw_df.columns)

In [88]:
big_col

['Symbol',
 'Symbol Name',
 'ROA',
 'ROA.1',
 'ROA.2',
 'ROA.3',
 'ROA.4',
 'ROA.5',
 'ROA.6',
 'ROA.7',
 'ROA.8',
 'ROA.9',
 'ROA.10',
 'ROA.11',
 'ROA.12',
 'ROA.13',
 'ROA.14',
 'ROA.15',
 'ROA.16',
 'ROA.17',
 'ROA.18',
 'ROA.19',
 'ROA.20',
 'ROA.21',
 'ROA.22',
 'ROA.23',
 'ROA.24',
 'ROA.25',
 'ROA.26',
 'ROA.27',
 'ROA.28',
 'ROA.29',
 'ROA.30',
 'ROA.31',
 'ROA.32',
 'ROA.33',
 'ROA.34',
 'ROA.35',
 'ROA.36',
 'ROA.37',
 'ROA.38',
 '부채비율',
 '부채비율.1',
 '부채비율.2',
 '부채비율.3',
 '부채비율.4',
 '부채비율.5',
 '부채비율.6',
 '부채비율.7',
 '부채비율.8',
 '부채비율.9',
 '부채비율.10',
 '부채비율.11',
 '부채비율.12',
 '부채비율.13',
 '부채비율.14',
 '부채비율.15',
 '부채비율.16',
 '부채비율.17',
 '부채비율.18',
 '부채비율.19',
 '부채비율.20',
 '부채비율.21',
 '부채비율.22',
 '부채비율.23',
 '부채비율.24',
 '부채비율.25',
 '부채비율.26',
 '부채비율.27',
 '부채비율.28',
 '부채비율.29',
 '부채비율.30',
 '부채비율.31',
 '부채비율.32',
 '부채비율.33',
 '부채비율.34',
 '부채비율.35',
 '부채비율.36',
 '부채비율.37',
 '부채비율.38',
 'PER',
 'PER.1',
 'PER.2',
 'PER.3',
 'PER.4',
 'PER.5',
 'PER.6',
 'PER.7',
 'PER.8',
 'PER.9',
 'PER.10',
 'PER.11',
 'PER.12',
 'PER.13',
 'PER.14',
 'PER.15',
 'PER.16',
 'PER.17',
 'PER.18',
 'PER.19',
 'PER.20',
 'PER.21',
 'PER.22',
 'PER.23',
 'PER.24',
 'PER.25',
 'PER.26',
 'PER.27',
 'PER.28',
 'PER.29',
 'PER.30',
 'PER.31',
 'PER.32',
 'PER.33',
 'PER.34',
 'PER.35',
 'PER.36',
 'PER.37',
 'PER.38',
 'PER.39',
 'PBR',
 'PBR.1',
 'PBR.2',
 'PBR.3',
 'PBR.4',
 'PBR.5',
 'PBR.6',
 'PBR.7',
 'PBR.8',
 'PBR.9',
 'PBR.10',
 'PBR.11',
 'PBR.12',
 'PBR.13',
 'PBR.14',
 'PBR.15',
 'PBR.16',
 'PBR.17',
 'PBR.18',
 'PBR.19',
 'PBR.20',
 'PBR.21',
 'PBR.22',
 'PBR.23',
 'PBR.24',
 'PBR.25',
 'PBR.26',
 'PBR.27',
 'PBR.28',
 'PBR.29',
 'PBR.30',
 'PBR.31',
 'PBR.32',
 'PBR.33',
 'PBR.34',
 'PBR.35',
 'PBR.36',
 'PBR.37',
 'PBR.38',
 'PBR.39',
 'PSR',
 'PSR.1',
 'PSR.2',
 'PSR.3',
 'PSR.4',
 'PSR.5',
 'PSR.6',
 'PSR.7',
 'PSR.8',
 'PSR.9',
 'PSR.10',
 'PSR.11',
 'PSR.12',
 'PSR.13',
 'PSR.14',
 'PSR.15',
 'PSR.16',
 'PSR.17',
 'PSR.18',
 'PSR.19',
 'PSR.20',
 'PSR.21',
 'PSR.22',
 'PSR.23',
 'PSR.24',
 'PSR.25',
 'PSR.26',
 'PSR.27',
 'PSR.28',
 'PSR.29',
 'PSR.30',
 'PSR.31',
 'PSR.32',
 'PSR.33',
 'PSR.34',
 'PSR.35',
 'PSR.36',
 'PSR.37',
 'PSR.38',
 'EV',
 'EV.1',
 'EV.2',
 'EV.3',
 'EV.4',
 'EV.5',
 'EV.6',
 'EV.7',
 'EV.8',
 'EV.9',
 'EV.10',
 'EV.11',
 'EV.12',
 'EV.13',
 'EV.14',
 'EV.15',
 'EV.16',
 'EV.17',
 'EV.18',
 'EV.19',
 'EV.20',
 'EV.21',
 'EV.22',
 'EV.23',
 'EV.24',
 'EV.25',
 'EV.26',
 'EV.27',
 'EV.28',
 'EV.29',
 'EV.30',
 'EV.31',
 'EV.32',
 'EV.33',
 'EV.34',
 'EV.35',
 'EV.36',
 'EV.37',
 'EV.38',
 'EBITDA',
 'EBITDA.1',
 'EBITDA.2',
 'EBITDA.3',
 'EBITDA.4',
 'EBITDA.5',
 'EBITDA.6',
 'EBITDA.7',
 'EBITDA.8',
 'EBITDA.9',
 'EBITDA.10',
 'EBITDA.11',
 'EBITDA.12',
 'EBITDA.13',
 'EBITDA.14',
 'EBITDA.15',
 'EBITDA.16',
 'EBITDA.17',
 'EBITDA.18',
 'EBITDA.19',
 'EBITDA.20',
 'EBITDA.21',
 'EBITDA.22',
 'EBITDA.23',
 'EBITDA.24',
 'EBITDA.25',
 'EBITDA.26',
 'EBITDA.27',
 'EBITDA.28',
 'EBITDA.29',
 'EBITDA.30',
 'EBITDA.31',
 'EBITDA.32',
 'EBITDA.33',
 'EBITDA.34',
 'EBITDA.35',
 'EBITDA.36',
 'EBITDA.37',
 'EBITDA.38',
 'EV/EBITDA',
 'EV/EBITDA.1',
 'EV/EBITDA.2',
 'EV/EBITDA.3',
 'EV/EBITDA.4',
 'EV/EBITDA.5',
 'EV/EBITDA.6',
 'EV/EBITDA.7',
 'EV/EBITDA.8',
 'EV/EBITDA.9',
 'EV/EBITDA.10',
 'EV/EBITDA.11',
 'EV/EBITDA.12',
 'EV/EBITDA.13',
 'EV/EBITDA.14',
 'EV/EBITDA.15',
 'EV/EBITDA.16',
 'EV/EBITDA.17',
 'EV/EBITDA.18',
 'EV/EBITDA.19',
 'EV/EBITDA.20',
 'EV/EBITDA.21',
 'EV/EBITDA.22',
 'EV/EBITDA.23',
 'EV/EBITDA.24',
 'EV/EBITDA.25',
 'EV/EBITDA.26',
 'EV/EBITDA.27',
 'EV/EBITDA.28',
 'EV/EBITDA.29',
 'EV/EBITDA.30',
 'EV/EBITDA.31',
 'EV/EBITDA.32',
 'EV/EBITDA.33',
 'EV/EBITDA.34',
 'EV/EBITDA.35',
 'EV/EBITDA.36',
 'EV/EBITDA.37',
 'EV/EBITDA.38',
 '유동자산',
 '유동자산.1',
 '유동자산.2',
 '유동자산.3',
 '유동자산.4',
 '유동자산.5',
 '유동자산.6',
 '유동자산.7',
 '유동자산.8',
 '내돈',
 '내돈.1',
 '내돈.2',
 '내돈.3',
 '내돈.4',
 '내돈.5',
 '내돈.6',
 '내돈.7',
 '내돈.8',
 '내돈.9',
 '내돈.10',
 '내돈.11',
 '내돈.12',
 '내돈.13',
 '내돈.14',
 '내돈.15',
 '내돈.16',
 '내돈.17',
 '내돈.18',
 '내돈.19',
 '내돈.20',
 '내돈.21',
 '내돈.22',
 '내돈.23',
 '내돈.24',
 '내돈.25',
 '내돈.26',
 '내돈.27',
 '내돈.28',
 '내돈.29',
 '내돈.30',
 '내돈.31',
 '내돈.32',
 '내돈.33',
 '내돈.34',
 '내돈.35',
 '내돈.36',
 '내돈.37',
 '내돈.38',
 '내돈.39',
 '시총',
 '시총.1',
 '시총.2',
 '시총.3',
 '시총.4',
 '시총.5',
 '시총.6',
 '시총.7',
 '시총.8',
 '시총.9',
 '시총.10',
 '시총.11',
 '시총.12',
 '시총.13',
 '시총.14',
 '시총.15',
 '시총.16',
 '시총.17',
 '시총.18',
 '시총.19',
 '시총.20',
 '시총.21',
 '시총.22',
 '시총.23',
 '시총.24',
 '시총.25',
 '시총.26',
 '시총.27',
 '시총.28',
 '시총.29',
 '시총.30',
 '시총.31',
 '시총.32',
 '시총.33',
 '시총.34',
 '시총.35',
 '시총.36',
 '시총.37',
 '시총.38',
 '시총.39',
 '영익',
 '영익.1',
 '영익.2',
 '영익.3',
 '영익.4',
 '영익.5',
 '영익.6',
 '영익.7',
 '영익.8',
 '영익.9',
 '영익.10',
 '영익.11',
 '영익.12',
 '영익.13',
 '영익.14',
 '영익.15',
 '영익.16',
 '영익.17',
 '영익.18',
 '영익.19',
 '영익.20',
 '영익.21',
 '영익.22',
 '영익.23',
 '영익.24',
 '영익.25',
 '영익.26',
 '영익.27',
 '영익.28',
 '영익.29',
 '영익.30',
 '영익.31',
 '영익.32',
 '영익.33',
 '영익.34',
 '영익.35',
 '영익.36',
 '영익.37',
 '영익.38',
 '영익.39',
 '순익',
 '순익.1',
 '순익.2',
 '순익.3',
 '순익.4',
 '순익.5',
 '순익.6',
 '순익.7',
 '순익.8',
 '순익.9',
 '순익.10',
 '순익.11',
 '순익.12',
 '순익.13',
 '순익.14',
 '순익.15',
 '순익.16',
 '순익.17',
 '순익.18',
 '순익.19',
 '순익.20',
 '순익.21',
 '순익.22',
 '순익.23',
 '순익.24',
 '순익.25',
 '순익.26',
 '순익.27',
 '순익.28',
 '순익.29',
 '순익.30',
 '순익.31',
 '순익.32',
 '순익.33',
 '순익.34',
 '순익.35',
 '순익.36',
 '순익.37',
 '순익.38',
 '순익.39',
 '영업활동현흐',
 '영업활동현흐.1',
 '영업활동현흐.2',
 '영업활동현흐.3',
 '영업활동현흐.4',
 '영업활동현흐.5',
 '영업활동현흐.6',
 '영업활동현흐.7',
 '영업활동현흐.8',
 '영업활동현흐.9',
 '영업활동현흐.10',
 '영업활동현흐.11',
 '영업활동현흐.12',
 '영업활동현흐.13',
 '영업활동현흐.14',
 '영업활동현흐.15',
 '영업활동현흐.16',
 '영업활동현흐.17',
 '영업활동현흐.18',
 '영업활동현흐.19',
 '영업활동현흐.20',
 '영업활동현흐.21',
 '영업활동현흐.22',
 '영업활동현흐.23',
 '영업활동현흐.24',
 '영업활동현흐.25',
 '영업활동현흐.26',
 '영업활동현흐.27',
 '영업활동현흐.28',
 '영업활동현흐.29',
 '영업활동현흐.30',
 '영업활동현흐.31',
 '영업활동현흐.32',
 '영업활동현흐.33',
 '영업활동현흐.34',
 '영업활동현흐.35',
 '영업활동현흐.36',
 '영업활동현흐.37',
 '영업활동현흐.38',
 '매출총이익율',
 '매출총이익율.1',
 '매출총이익율.2',
 '매출총이익율.3',
 '매출총이익율.4',
 '매출총이익율.5',
 '매출총이익율.6',
 '매출총이익율.7',
 '매출총이익율.8',
 '매출총이익율.9',
 '매출총이익율.10',
 '매출총이익율.11',
 '매출총이익율.12',
 '매출총이익율.13',
 '매출총이익율.14',
 '매출총이익율.15',
 '매출총이익율.16',
 '매출총이익율.17',
 '매출총이익율.18',
 '매출총이익율.19',
 '매출총이익율.20',
 '매출총이익율.21',
 '매출총이익율.22',
 '매출총이익율.23',
 '매출총이익율.24',
 '매출총이익율.25',
 '매출총이익율.26',
 '매출총이익율.27',
 '매출총이익율.28',
 '매출총이익율.29',
 '매출총이익율.30',
 '매출총이익율.31',
 '매출총이익율.32',
 '매출총이익율.33',
 '매출총이익율.34',
 '매출총이익율.35',
 '매출총이익율.36',
 '매출총이익율.37',
 '매출총이익율.38',
 '매출',
 '매출.1',
 '매출.2',
 '매출.3',
 '매출.4',
 '매출.5',
 '매출.6',
 '매출.7',
 '매출.8',
 '매출.9',
 '매출.10',
 '매출.11',
 '매출.12',
 '매출.13',
 '매출.14',
 '매출.15',
 '매출.16',
 '매출.17',
 '매출.18',
 '매출.19',
 '매출.20',
 '매출.21',
 '매출.22',
 '매출.23',
 '매출.24',
 '매출.25',
 '매출.26',
 '매출.27',
 '매출.28',
 '매출.29',
 '매출.30',
 '매출.31',
 '매출.32',
 '매출.33',
 '매출.34',
 '매출.35',
 '매출.36',
 '매출.37',
 '매출.38',
 '매출.39',
 '총자산',
 '총자산.1',
 '총자산.2',
 '총자산.3',
 '총자산.4',
 '총자산.5',
 '총자산.6',
 '총자산.7',
 '총자산.8',
 'DPS',
 'DPS.1',
 'DPS.2',
 'DPS.3',
 'DPS.4',
 'DPS.5',
 'DPS.6',
 'DPS.7',
 'DPS.8',
 'DPS.9',
 'DPS.10',
 'DPS.11',
 'DPS.12',
 'DPS.13',
 'DPS.14',
 'DPS.15',
 'DPS.16',
 'DPS.17',
 'DPS.18',
 'DPS.19',
 'DPS.20',
 'DPS.21',
 'DPS.22',
 'DPS.23',
 'DPS.24',
 'DPS.25',
 'DPS.26',
 'DPS.27',
 'DPS.28',
 'DPS.29',
 'DPS.30',
 'DPS.31',
 'DPS.32',
 'DPS.33',
 'DPS.34',
 'DPS.35',
 'DPS.36',
 'DPS.37',
 'DPS.38']

In [89]:
new_big_col = []
for i in big_col:
    new_big_col.append(i.split('.')[0])

In [90]:
new_big_col

['Symbol',
 'Symbol Name',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 '유동자산',
 '유동자산',
 '유동자산',
 '유동자산',
 '유동자산',
 '유동자산',
 '유동자산',
 '유동자산',
 '유동자산',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '총자산',
 '총자산',
 '총자산',
 '총자산',
 '총자산',
 '총자산',
 '총자산',
 '총자산',
 '총자산',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS']

In [91]:
small_col = list(raw_df.loc[0])

In [92]:
small_col

[nan,
 nan,
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '18/3Q',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '18/3Q',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '9년',
 '10년',
 '11년',
 '12년',
 '13년',
 '14년',
 '15년',
 '16년',
 '17년',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '18/3Q',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '18/3Q',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '18/3Q',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '18/3Q',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '18/3Q',
 '9년',
 '10년',
 '11년',
 '12년',
 '13년',
 '14년',
 '15년',
 '16년',
 '17년',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q']

In [93]:
small_col[0] = new_big_col[0]
small_col[1] = new_big_col[1]

In [94]:
small_col

['Symbol',
 'Symbol Name',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '18/3Q',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '18/3Q',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '9년',
 '10년',
 '11년',
 '12년',
 '13년',
 '14년',
 '15년',
 '16년',
 '17년',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '18/3Q',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '18/3Q',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '18/3Q',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '18/3Q',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '18/3Q',
 '9년',
 '10년',
 '11년',
 '12년',
 '13년',
 '14년',
 '15년',
 '16년',
 '17년',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q']

In [95]:
raw_df.columns = [new_big_col, small_col]
raw_df.columns

MultiIndex([(     'Symbol',      'Symbol'),
            ('Symbol Name', 'Symbol Name'),
            (        'ROA',       '08/4Q'),
            (        'ROA',       '09/1Q'),
            (        'ROA',       '09/2Q'),
            (        'ROA',       '09/3Q'),
            (        'ROA',       '09/4Q'),
            (        'ROA',       '10/1Q'),
            (        'ROA',       '10/2Q'),
            (        'ROA',       '10/3Q'),
            ...
            (        'DPS',       '16/1Q'),
            (        'DPS',       '16/2Q'),
            (        'DPS',       '16/3Q'),
            (        'DPS',       '16/4Q'),
            (        'DPS',       '17/1Q'),
            (        'DPS',       '17/2Q'),
            (        'DPS',       '17/3Q'),
            (        'DPS',       '17/4Q'),
            (        'DPS',       '18/1Q'),
            (        'DPS',       '18/2Q')],
           length=651)

In [96]:
raw_df.head()

    Symbol Symbol Name    ROA                                            \
    Symbol Symbol Name  08/4Q  09/1Q  09/2Q  09/3Q  09/4Q  10/1Q  10/2Q
0      NaN         NaN  08/4Q  09/1Q  09/2Q  09/3Q  09/4Q  10/1Q  10/2Q
1  A005930        삼성전자   7.62   5.24   3.78   5.46   6.93   8.74  10.53
2  A000660      SK하이닉스      0      0      0      0      0  12.57  18.73
3  A068270        셀트리온   2.92   4.89   8.63    7.3  10.48  11.75  14.02
4  A207940    삼성바이오로직스      0      0      0      0      0      0      0

          ...    DPS                                                          \
   10/3Q  ...  16/1Q  16/2Q  16/3Q  16/4Q  17/1Q  17/2Q  17/3Q  17/4Q  18/1Q
0  10/3Q  ...  16/1Q  16/2Q  16/3Q  16/4Q  17/1Q  17/2Q  17/3Q  17/4Q  18/1Q
1  11.46  ...    570    570    570    570    850    850    850    850    850
2  25.35  ...    600    600    600    600   1000   1000   1000   1000   1000
3  17.22  ...  46.73  46.73  46.73  46.73  19.61  19.61  19.61  19.61  19.61
4      0  ...      0      0      0      0      0      0      0      0      0


   18/2Q
0  18/2Q
1    850
2   1000
3  19.61
4      0

[5 rows x 651 columns]

In [97]:
raw_df.isnull().sum(axis=1)

0       2
1       0
2       0
3       0
4       0
       ..
2049    0
2050    0
2051    0
2052    0
2053    0
Length: 2054, dtype: int64

In [98]:
raw_df.isnull().sum(axis=1).sum()

2

In [99]:
finance_df = raw_df.drop(0)

In [100]:
finance_df.index = finance_df['Symbol']['Symbol']

In [101]:
finance_df

          Symbol Symbol Name   ROA                                         \
          Symbol Symbol Name 08/4Q 09/1Q 09/2Q 09/3Q  09/4Q  10/1Q  10/2Q
Symbol
A005930  A005930        삼성전자  7.62  5.24  3.78  5.46   6.93   8.74  10.53
A000660  A000660      SK하이닉스     0     0     0     0      0  12.57  18.73
A068270  A068270        셀트리온  2.92  4.89  8.63   7.3  10.48  11.75  14.02
A207940  A207940    삼성바이오로직스     0     0     0     0      0      0      0
A005380  A005380         현대차   4.5  3.94  4.67   6.6   8.36  10.01     10
...          ...         ...   ...   ...   ...   ...    ...    ...    ...
A297570  A297570   IBKS제9호스팩     0     0     0     0      0      0      0
A279410  A279410   한화에이스스팩4호     0     0     0     0      0      0      0
A258790  A258790   케이비제11호스팩     0     0     0     0      0      0      0
A264290  A264290   한화에이스스팩3호     0     0     0     0      0      0      0
A010400  A010400     우진아이엔에스     0     0     0     0      0      0      0

                ...    DPS                                                   \
         10/3Q  ...  16/1Q  16/2Q  16/3Q  16/4Q  17/1Q  17/2Q  17/3Q  17/4Q
Symbol          ...
A005930  11.46  ...    570    570    570    570    850    850    850    850
A000660  25.35  ...    600    600    600    600   1000   1000   1000   1000
A068270  17.22  ...  46.73  46.73  46.73  46.73  19.61  19.61  19.61  19.61
A207940      0  ...      0      0      0      0      0      0      0      0
A005380   9.82  ...   4000   4000   4000   4000   4000   4000   4000   4000
...        ...  ...    ...    ...    ...    ...    ...    ...    ...    ...
A297570      0  ...      0      0      0      0      0      0      0      0
A279410      0  ...      0      0      0      0      0      0      0      0
A258790      0  ...      0      0      0      0      0      0      0      0
A264290      0  ...      0      0      0      0      0      0      0      0
A010400      0  ...      0      0      0      0      0      0      0      0


         18/1Q  18/2Q
Symbol
A005930    850    850
A000660   1000   1000
A068270  19.61  19.61
A207940      0      0
A005380   4000   4000
...        ...    ...
A297570      0      0
A279410      0      0
A258790      0      0
A264290      0      0
A010400      0      0

[2053 rows x 651 columns]

In [102]:
finance_df.columns

MultiIndex([(     'Symbol',      'Symbol'),
            ('Symbol Name', 'Symbol Name'),
            (        'ROA',       '08/4Q'),
            (        'ROA',       '09/1Q'),
            (        'ROA',       '09/2Q'),
            (        'ROA',       '09/3Q'),
            (        'ROA',       '09/4Q'),
            (        'ROA',       '10/1Q'),
            (        'ROA',       '10/2Q'),
            (        'ROA',       '10/3Q'),
            ...
            (        'DPS',       '16/1Q'),
            (        'DPS',       '16/2Q'),
            (        'DPS',       '16/3Q'),
            (        'DPS',       '16/4Q'),
            (        'DPS',       '17/1Q'),
            (        'DPS',       '17/2Q'),
            (        'DPS',       '17/3Q'),
            (        'DPS',       '17/4Q'),
            (        'DPS',       '18/1Q'),
            (        'DPS',       '18/2Q')],
           length=651)

In [103]:
finance_df

          Symbol Symbol Name   ROA                                         \
          Symbol Symbol Name 08/4Q 09/1Q 09/2Q 09/3Q  09/4Q  10/1Q  10/2Q
Symbol
A005930  A005930        삼성전자  7.62  5.24  3.78  5.46   6.93   8.74  10.53
A000660  A000660      SK하이닉스     0     0     0     0      0  12.57  18.73
A068270  A068270        셀트리온  2.92  4.89  8.63   7.3  10.48  11.75  14.02
A207940  A207940    삼성바이오로직스     0     0     0     0      0      0      0
A005380  A005380         현대차   4.5  3.94  4.67   6.6   8.36  10.01     10
...          ...         ...   ...   ...   ...   ...    ...    ...    ...
A297570  A297570   IBKS제9호스팩     0     0     0     0      0      0      0
A279410  A279410   한화에이스스팩4호     0     0     0     0      0      0      0
A258790  A258790   케이비제11호스팩     0     0     0     0      0      0      0
A264290  A264290   한화에이스스팩3호     0     0     0     0      0      0      0
A010400  A010400     우진아이엔에스     0     0     0     0      0      0      0

                ...    DPS                                                   \
         10/3Q  ...  16/1Q  16/2Q  16/3Q  16/4Q  17/1Q  17/2Q  17/3Q  17/4Q
Symbol          ...
A005930  11.46  ...    570    570    570    570    850    850    850    850
A000660  25.35  ...    600    600    600    600   1000   1000   1000   1000
A068270  17.22  ...  46.73  46.73  46.73  46.73  19.61  19.61  19.61  19.61
A207940      0  ...      0      0      0      0      0      0      0      0
A005380   9.82  ...   4000   4000   4000   4000   4000   4000   4000   4000
...        ...  ...    ...    ...    ...    ...    ...    ...    ...    ...
A297570      0  ...      0      0      0      0      0      0      0      0
A279410      0  ...      0      0      0      0      0      0      0      0
A258790      0  ...      0      0      0      0      0      0      0      0
A264290      0  ...      0      0      0      0      0      0      0      0
A010400      0  ...      0      0      0      0      0      0      0      0


         18/1Q  18/2Q
Symbol
A005930    850    850
A000660   1000   1000
A068270  19.61  19.61
A207940      0      0
A005380   4000   4000
...        ...    ...
A297570      0      0
A279410      0      0
A258790      0      0
A264290      0      0
A010400      0      0

[2053 rows x 651 columns]

In [105]:
date = '17/2Q'
finance_df[[('PBR', date), ('ROA', date)]]

          PBR    ROA
        17/2Q  17/2Q
Symbol
A005930   1.6  10.95
A000660  1.77  17.58
A068270  6.41   9.61
A207940   4.8      0
A005380  0.51   2.43
...       ...    ...
A297570     0      0
A279410     0      0
A258790   1.1      0
A264290  1.22      0
A010400     0   3.29

[2053 rows x 2 columns]

In [116]:
def finance_data_preprocessing(path):
    raw_data = pd.read_excel(path)
    
    big_col = list(raw_data.columns)
    for num, temp in enumerate(big_col):
        if '.' in temp:
            big_col[num] = temp.split('.')[0]
          
    small_col = list(raw_data.loc[0])
    small_col[0] = big_col[0]
    small_col[1] = big_col[1]

    raw_data.columns = [big_col, small_col]
    raw_data = raw_data.drop(0)

    raw_data.index = raw_data['Symbol']['Symbol']
    del raw_data['Symbol']

    return raw_data

In [115]:
finance_data_preprocessing('data_files/재무데이터 수정.xlsx')

['Symbol', 'Symbol Name', 'ROA', 'ROA.1', 'ROA.2', 'ROA.3', 'ROA.4', 'ROA.5', 'ROA.6', 'ROA.7', 'ROA.8', 'ROA.9', 'ROA.10', 'ROA.11', 'ROA.12', 'ROA.13', 'ROA.14', 'ROA.15', 'ROA.16', 'ROA.17', 'ROA.18', 'ROA.19', 'ROA.20', 'ROA.21', 'ROA.22', 'ROA.23', 'ROA.24', 'ROA.25', 'ROA.26', 'ROA.27', 'ROA.28', 'ROA.29', 'ROA.30', 'ROA.31', 'ROA.32', 'ROA.33', 'ROA.34', 'ROA.35', 'ROA.36', 'ROA.37', 'ROA.38', '부채비율', '부채비율.1', '부채비율.2', '부채비율.3', '부채비율.4', '부채비율.5', '부채비율.6', '부채비율.7', '부채비율.8', '부채비율.9', '부채비율.10', '부채비율.11', '부채비율.12', '부채비율.13', '부채비율.14', '부채비율.15', '부채비율.16', '부채비율.17', '부채비율.18', '부채비율.19', '부채비율.20', '부채비율.21', '부채비율.22', '부채비율.23', '부채비율.24', '부채비율.25', '부채비율.26', '부채비율.27', '부채비율.28', '부채비율.29', '부채비율.30', '부채비율.31', '부채비율.32', '부채비율.33', '부채비율.34', '부채비율.35', '부채비율.36', '부채비율.37', '부채비율.38', 'PER', 'PER.1', 'PER.2', 'PER.3', 'PER.4', 'PER.5', 'PER.6', 'PER.7', 'PER.8', 'PER.9', 'PER.10', 'PER.11', 'PER.12', 'PER.13', 'PER.14', 'PER.15', 'PER.16', 'PER.17', 'PER.18', 'PER.19', 'PER.20', 'PER.21', 'PER.22', 'PER.23', 'PER.24', 'PER.25', 'PER.26', 'PER.27', 'PER.28', 'PER.29', 'PER.30', 'PER.31', 'PER.32', 'PER.33', 'PER.34', 'PER.35', 'PER.36', 'PER.37', 'PER.38', 'PER.39', 'PBR', 'PBR.1', 'PBR.2', 'PBR.3', 'PBR.4', 'PBR.5', 'PBR.6', 'PBR.7', 'PBR.8', 'PBR.9', 'PBR.10', 'PBR.11', 'PBR.12', 'PBR.13', 'PBR.14', 'PBR.15', 'PBR.16', 'PBR.17', 'PBR.18', 'PBR.19', 'PBR.20', 'PBR.21', 'PBR.22', 'PBR.23', 'PBR.24', 'PBR.25', 'PBR.26', 'PBR.27', 'PBR.28', 'PBR.29', 'PBR.30', 'PBR.31', 'PBR.32', 'PBR.33', 'PBR.34', 'PBR.35', 'PBR.36', 'PBR.37', 'PBR.38', 'PBR.39', 'PSR', 'PSR.1', 'PSR.2', 'PSR.3', 'PSR.4', 'PSR.5', 'PSR.6', 'PSR.7', 'PSR.8', 'PSR.9', 'PSR.10', 'PSR.11', 'PSR.12', 'PSR.13', 'PSR.14', 'PSR.15', 'PSR.16', 'PSR.17', 'PSR.18', 'PSR.19', 'PSR.20', 'PSR.21', 'PSR.22', 'PSR.23', 'PSR.24', 'PSR.25', 'PSR.26', 'PSR.27', 'PSR.28', 'PSR.29', 'PSR.30', 'PSR.31', 'PSR.32', 'PSR.33', 'PSR.34', 'PSR.35', 'PSR.36', 'PSR.37', 'PSR.38', 'EV', 'EV.1', 'EV.2', 'EV.3', 'EV.4', 'EV.5', 'EV.6', 'EV.7', 'EV.8', 'EV.9', 'EV.10', 'EV.11', 'EV.12', 'EV.13', 'EV.14', 'EV.15', 'EV.16', 'EV.17', 'EV.18', 'EV.19', 'EV.20', 'EV.21', 'EV.22', 'EV.23', 'EV.24', 'EV.25', 'EV.26', 'EV.27', 'EV.28', 'EV.29', 'EV.30', 'EV.31', 'EV.32', 'EV.33', 'EV.34', 'EV.35', 'EV.36', 'EV.37', 'EV.38', 'EBITDA', 'EBITDA.1', 'EBITDA.2', 'EBITDA.3', 'EBITDA.4', 'EBITDA.5', 'EBITDA.6', 'EBITDA.7', 'EBITDA.8', 'EBITDA.9', 'EBITDA.10', 'EBITDA.11', 'EBITDA.12', 'EBITDA.13', 'EBITDA.14', 'EBITDA.15', 'EBITDA.16', 'EBITDA.17', 'EBITDA.18', 'EBITDA.19', 'EBITDA.20', 'EBITDA.21', 'EBITDA.22', 'EBITDA.23', 'EBITDA.24', 'EBITDA.25', 'EBITDA.26', 'EBITDA.27', 'EBITDA.28', 'EBITDA.29', 'EBITDA.30', 'EBITDA.31', 'EBITDA.32', 'EBITDA.33', 'EBITDA.34', 'EBITDA.35', 'EBITDA.36', 'EBITDA.37', 'EBITDA.38', 'EV/EBITDA', 'EV/EBITDA.1', 'EV/EBITDA.2', 'EV/EBITDA.3', 'EV/EBITDA.4', 'EV/EBITDA.5', 'EV/EBITDA.6', 'EV/EBITDA.7', 'EV/EBITDA.8', 'EV/EBITDA.9', 'EV/EBITDA.10', 'EV/EBITDA.11', 'EV/EBITDA.12', 'EV/EBITDA.13', 'EV/EBITDA.14', 'EV/EBITDA.15', 'EV/EBITDA.16', 'EV/EBITDA.17', 'EV/EBITDA.18', 'EV/EBITDA.19', 'EV/EBITDA.20', 'EV/EBITDA.21', 'EV/EBITDA.22', 'EV/EBITDA.23', 'EV/EBITDA.24', 'EV/EBITDA.25', 'EV/EBITDA.26', 'EV/EBITDA.27', 'EV/EBITDA.28', 'EV/EBITDA.29', 'EV/EBITDA.30', 'EV/EBITDA.31', 'EV/EBITDA.32', 'EV/EBITDA.33', 'EV/EBITDA.34', 'EV/EBITDA.35', 'EV/EBITDA.36', 'EV/EBITDA.37', 'EV/EBITDA.38', '유동자산', '유동자산.1', '유동자산.2', '유동자산.3', '유동자산.4', '유동자산.5', '유동자산.6', '유동자산.7', '유동자산.8', '내돈', '내돈.1', '내돈.2', '내돈.3', '내돈.4', '내돈.5', '내돈.6', '내돈.7', '내돈.8', '내돈.9', '내돈.10', '내돈.11', '내돈.12', '내돈.13', '내돈.14', '내돈.15', '내돈.16', '내돈.17', '내돈.18', '내돈.19', '내돈.20', '내돈.21', '내돈.22', '내돈.23', '내돈.24', '내돈.25', '내돈.26', '내돈.27', '내돈.28', '내돈.29', '내돈.30', '내돈.31', '내돈.32', '내돈.33', '내돈.34', '내돈.35', '내돈.36', '내돈.37', '내돈.38', '내돈.39', '시총', '시총.1', '시총.2', '시총.3', '시총.4', '시총.5', '시총.6', '시총.7', '시총.8', '시총.9', '시총.10', '시총.11', '시총.12', '시총.13', '시총.14', '시총.15', '시총.16', '시총.17', '시총.18', '시총.19', '시총.20', '시총.21', '시총.22', '시총.23', '시총.24', '시총.25', '시총.26', '시총.27', '시총.28', '시총.29', '시총.30', '시총.31', '시총.32', '시총.33', '시총.34', '시총.35', '시총.36', '시총.37', '시총.38', '시총.39', '영익', '영익.1', '영익.2', '영익.3', '영익.4', '영익.5', '영익.6', '영익.7', '영익.8', '영익.9', '영익.10', '영익.11', '영익.12', '영익.13', '영익.14', '영익.15', '영익.16', '영익.17', '영익.18', '영익.19', '영익.20', '영익.21', '영익.22', '영익.23', '영익.24', '영익.25', '영익.26', '영익.27', '영익.28', '영익.29', '영익.30', '영익.31', '영익.32', '영익.33', '영익.34', '영익.35', '영익.36', '영익.37', '영익.38', '영익.39', '순익', '순익.1', '순익.2', '순익.3', '순익.4', '순익.5', '순익.6', '순익.7', '순익.8', '순익.9', '순익.10', '순익.11', '순익.12', '순익.13', '순익.14', '순익.15', '순익.16', '순익.17', '순익.18', '순익.19', '순익.20', '순익.21', '순익.22', '순익.23', '순익.24', '순익.25', '순익.26', '순익.27', '순익.28', '순익.29', '순익.30', '순익.31', '순익.32', '순익.33', '순익.34', '순익.35', '순익.36', '순익.37', '순익.38', '순익.39', '영업활동현흐', '영업활동현흐.1', '영업활동현흐.2', '영업활동현흐.3', '영업활동현흐.4', '영업활동현흐.5', '영업활동현흐.6', '영업활동현흐.7', '영업활동현흐.8', '영업활동현흐.9', '영업활동현흐.10', '영업활동현흐.11', '영업활동현흐.12', '영업활동현흐.13', '영업활동현흐.14', '영업활동현흐.15', '영업활동현흐.16', '영업활동현흐.17', '영업활동현흐.18', '영업활동현흐.19', '영업활동현흐.20', '영업활동현흐.21', '영업활동현흐.22', '영업활동현흐.23', '영업활동현흐.24', '영업활동현흐.25', '영업활동현흐.26', '영업활동현흐.27', '영업활동현흐.28', '영업활동현흐.29', '영업활동현흐.30', '영업활동현흐.31', '영업활동현흐.32', '영업활동현흐.33', '영업활동현흐.34', '영업활동현흐.35', '영업활동현흐.36', '영업활동현흐.37', '영업활동현흐.38', '매출총이익율', '매출총이익율.1', '매출총이익율.2', '매출총이익율.3', '매출총이익율.4', '매출총이익율.5', '매출총이익율.6', '매출총이익율.7', '매출총이익율.8', '매출총이익율.9', '매출총이익율.10', '매출총이익율.11', '매출총이익율.12', '매출총이익율.13', '매출총이익율.14', '매출총이익율.15', '매출총이익율.16', '매출총이익율.17', '매출총이익율.18', '매출총이익율.19', '매출총이익율.20', '매출총이익율.21', '매출총이익율.22', '매출총이익율.23', '매출총이익율.24', '매출총이익율.25', '매출총이익율.26', '매출총이익율.27', '매출총이익율.28', '매출총이익율.29', '매출총이익율.30', '매출총이익율.31', '매출총이익율.32', '매출총이익율.33', '매출총이익율.34', '매출총이익율.35', '매출총이익율.36', '매출총이익율.37', '매출총이익율.38', '매출', '매출.1', '매출.2', '매출.3', '매출.4', '매출.5', '매출.6', '매출.7', '매출.8', '매출.9', '매출.10', '매출.11', '매출.12', '매출.13', '매출.14', '매출.15', '매출.16', '매출.17', '매출.18', '매출.19', '매출.20', '매출.21', '매출.22', '매출.23', '매출.24', '매출.25', '매출.26', '매출.27', '매출.28', '매출.29', '매출.30', '매출.31', '매출.32', '매출.33', '매출.34', '매출.35', '매출.36', '매출.37', '매출.38', '매출.39', '총자산', '총자산.1', '총자산.2', '총자산.3', '총자산.4', '총자산.5', '총자산.6', '총자산.7', '총자산.8', 'DPS', 'DPS.1', 'DPS.2', 'DPS.3', 'DPS.4', 'DPS.5', 'DPS.6', 'DPS.7', 'DPS.8', 'DPS.9', 'DPS.10', 'DPS.11', 'DPS.12', 'DPS.13', 'DPS.14', 'DPS.15', 'DPS.16', 'DPS.17', 'DPS.18', 'DPS.19', 'DPS.20', 'DPS.21', 'DPS.22', 'DPS.23', 'DPS.24', 'DPS.25', 'DPS.26', 'DPS.27', 'DPS.28', 'DPS.29', 'DPS.30', 'DPS.31', 'DPS.32', 'DPS.33', 'DPS.34', 'DPS.35', 'DPS.36', 'DPS.37', 'DPS.38']
0 Symbol
1 Symbol Name
2 ROA
3 ROA.1
4 ROA.2
5 ROA.3
6 ROA.4
7 ROA.5
8 ROA.6
9 ROA.7
10 ROA.8
11 ROA.9
12 ROA.10
13 ROA.11
14 ROA.12
15 ROA.13
16 ROA.14
17 ROA.15
18 ROA.16
19 ROA.17
20 ROA.18
21 ROA.19
22 ROA.20
23 ROA.21
24 ROA.22
25 ROA.23
26 ROA.24
27 ROA.25
28 ROA.26
29 ROA.27
30 ROA.28
31 ROA.29
32 ROA.30
33 ROA.31
34 ROA.32
35 ROA.33
36 ROA.34
37 ROA.35
38 ROA.36
39 ROA.37
40 ROA.38
41 부채비율
42 부채비율.1
43 부채비율.2
44 부채비율.3
45 부채비율.4
46 부채비율.5
47 부채비율.6
48 부채비율.7
49 부채비율.8
50 부채비율.9
51 부채비율.10
52 부채비율.11
53 부채비율.12
54 부채비율.13
55 부채비율.14
56 부채비율.15
57 부채비율.16
58 부채비율.17
59 부채비율.18
60 부채비율.19
61 부채비율.20
62 부채비율.21
63 부채비율.22
64 부채비율.23
65 부채비율.24
66 부채비율.25
67 부채비율.26
68 부채비율.27
69 부채비율.28
70 부채비율.29
71 부채비율.30
72 부채비율.31
73 부채비율.32
74 부채비율.33
75 부채비율.34
76 부채비율.35
77 부채비율.36
78 부채비율.37
79 부채비율.38
80 PER
81 PER.1
82 PER.2
83 PER.3
84 PER.4
85 PER.5
86 PER.6
87 PER.7
88 PER.8
89 PER.9
90 PER.10
91 PER.11
92 PER.12
93 PER.13
94 PER.14
95 PER.15
96 PER.16
97 PER.17
98 PER.18
99 PER.19
100 PER.20
101 PER.21
102 PER.22
103 PER.23
104 PER.24
105 PER.25
106 PER.26
107 PER.27
108 PER.28
109 PER.29
110 PER.30
111 PER.31
112 PER.32
113 PER.33
114 PER.34
115 PER.35
116 PER.36
117 PER.37
118 PER.38
119 PER.39
120 PBR
121 PBR.1
122 PBR.2
123 PBR.3
124 PBR.4
125 PBR.5
126 PBR.6
127 PBR.7
128 PBR.8
129 PBR.9
130 PBR.10
131 PBR.11
132 PBR.12
133 PBR.13
134 PBR.14
135 PBR.15
136 PBR.16
137 PBR.17
138 PBR.18
139 PBR.19
140 PBR.20
141 PBR.21
142 PBR.22
143 PBR.23
144 PBR.24
145 PBR.25
146 PBR.26
147 PBR.27
148 PBR.28
149 PBR.29
150 PBR.30
151 PBR.31
152 PBR.32
153 PBR.33
154 PBR.34
155 PBR.35
156 PBR.36
157 PBR.37
158 PBR.38
159 PBR.39
160 PSR
161 PSR.1
162 PSR.2
163 PSR.3
164 PSR.4
165 PSR.5
166 PSR.6
167 PSR.7
168 PSR.8
169 PSR.9
170 PSR.10
171 PSR.11
172 PSR.12
173 PSR.13
174 PSR.14
175 PSR.15
176 PSR.16
177 PSR.17
178 PSR.18
179 PSR.19
180 PSR.20
181 PSR.21
182 PSR.22
183 PSR.23
184 PSR.24
185 PSR.25
186 PSR.26
187 PSR.27
188 PSR.28
189 PSR.29
190 PSR.30
191 PSR.31
192 PSR.32
193 PSR.33
194 PSR.34
195 PSR.35
196 PSR.36
197 PSR.37
198 PSR.38
199 EV
200 EV.1
201 EV.2
202 EV.3
203 EV.4
204 EV.5
205 EV.6
206 EV.7
207 EV.8
208 EV.9
209 EV.10
210 EV.11
211 EV.12
212 EV.13
213 EV.14
214 EV.15
215 EV.16
216 EV.17
217 EV.18
218 EV.19
219 EV.20
220 EV.21
221 EV.22
222 EV.23
223 EV.24
224 EV.25
225 EV.26
226 EV.27
227 EV.28
228 EV.29
229 EV.30
230 EV.31
231 EV.32
232 EV.33
233 EV.34
234 EV.35
235 EV.36
236 EV.37
237 EV.38
238 EBITDA
239 EBITDA.1
240 EBITDA.2
241 EBITDA.3
242 EBITDA.4
243 EBITDA.5
244 EBITDA.6
245 EBITDA.7
246 EBITDA.8
247 EBITDA.9
248 EBITDA.10
249 EBITDA.11
250 EBITDA.12
251 EBITDA.13
252 EBITDA.14
253 EBITDA.15
254 EBITDA.16
255 EBITDA.17
256 EBITDA.18
257 EBITDA.19
258 EBITDA.20
259 EBITDA.21
260 EBITDA.22
261 EBITDA.23
262 EBITDA.24
263 EBITDA.25
264 EBITDA.26
265 EBITDA.27
266 EBITDA.28
267 EBITDA.29
268 EBITDA.30
269 EBITDA.31
270 EBITDA.32
271 EBITDA.33
272 EBITDA.34
273 EBITDA.35
274 EBITDA.36
275 EBITDA.37
276 EBITDA.38
277 EV/EBITDA
278 EV/EBITDA.1
279 EV/EBITDA.2
280 EV/EBITDA.3
281 EV/EBITDA.4
282 EV/EBITDA.5
283 EV/EBITDA.6
284 EV/EBITDA.7
285 EV/EBITDA.8
286 EV/EBITDA.9
287 EV/EBITDA.10
288 EV/EBITDA.11
289 EV/EBITDA.12
290 EV/EBITDA.13
291 EV/EBITDA.14
292 EV/EBITDA.15
293 EV/EBITDA.16
294 EV/EBITDA.17
295 EV/EBITDA.18
296 EV/EBITDA.19
297 EV/EBITDA.20
298 EV/EBITDA.21
299 EV/EBITDA.22
300 EV/EBITDA.23
301 EV/EBITDA.24
302 EV/EBITDA.25
303 EV/EBITDA.26
304 EV/EBITDA.27
305 EV/EBITDA.28
306 EV/EBITDA.29
307 EV/EBITDA.30
308 EV/EBITDA.31
309 EV/EBITDA.32
310 EV/EBITDA.33
311 EV/EBITDA.34
312 EV/EBITDA.35
313 EV/EBITDA.36
314 EV/EBITDA.37
315 EV/EBITDA.38
316 유동자산
317 유동자산.1
318 유동자산.2
319 유동자산.3
320 유동자산.4
321 유동자산.5
322 유동자산.6
323 유동자산.7
324 유동자산.8
325 내돈
326 내돈.1
327 내돈.2
328 내돈.3
329 내돈.4
330 내돈.5
331 내돈.6
332 내돈.7
333 내돈.8
334 내돈.9
335 내돈.10
336 내돈.11
337 내돈.12
338 내돈.13
339 내돈.14
340 내돈.15
341 내돈.16
342 내돈.17
343 내돈.18
344 내돈.19
345 내돈.20
346 내돈.21
347 내돈.22
348 내돈.23
349 내돈.24
350 내돈.25
351 내돈.26
352 내돈.27
353 내돈.28
354 내돈.29
355 내돈.30
356 내돈.31
357 내돈.32
358 내돈.33
359 내돈.34
360 내돈.35
361 내돈.36
362 내돈.37
363 내돈.38
364 내돈.39
365 시총
366 시총.1
367 시총.2
368 시총.3
369 시총.4
370 시총.5
371 시총.6
372 시총.7
373 시총.8
374 시총.9
375 시총.10
376 시총.11
377 시총.12
378 시총.13
379 시총.14
380 시총.15
381 시총.16
382 시총.17
383 시총.18
384 시총.19
385 시총.20
386 시총.21
387 시총.22
388 시총.23
389 시총.24
390 시총.25
391 시총.26
392 시총.27
393 시총.28
394 시총.29
395 시총.30
396 시총.31
397 시총.32
398 시총.33
399 시총.34
400 시총.35
401 시총.36
402 시총.37
403 시총.38
404 시총.39
405 영익
406 영익.1
407 영익.2
408 영익.3
409 영익.4
410 영익.5
411 영익.6
412 영익.7
413 영익.8
414 영익.9
415 영익.10
416 영익.11
417 영익.12
418 영익.13
419 영익.14
420 영익.15
421 영익.16
422 영익.17
423 영익.18
424 영익.19
425 영익.20
426 영익.21
427 영익.22
428 영익.23
429 영익.24
430 영익.25
431 영익.26
432 영익.27
433 영익.28
434 영익.29
435 영익.30
436 영익.31
437 영익.32
438 영익.33
439 영익.34
440 영익.35
441 영익.36
442 영익.37
443 영익.38
444 영익.39
445 순익
446 순익.1
447 순익.2
448 순익.3
449 순익.4
450 순익.5
451 순익.6
452 순익.7
453 순익.8
454 순익.9
455 순익.10
456 순익.11
457 순익.12
458 순익.13
459 순익.14
460 순익.15
461 순익.16
462 순익.17
463 순익.18
464 순익.19
465 순익.20
466 순익.21
467 순익.22
468 순익.23
469 순익.24
470 순익.25
471 순익.26
472 순익.27
473 순익.28
474 순익.29
475 순익.30
476 순익.31
477 순익.32
478 순익.33
479 순익.34
480 순익.35
481 순익.36
482 순익.37
483 순익.38
484 순익.39
485 영업활동현흐
486 영업활동현흐.1
487 영업활동현흐.2
488 영업활동현흐.3
489 영업활동현흐.4
490 영업활동현흐.5
491 영업활동현흐.6
492 영업활동현흐.7
493 영업활동현흐.8
494 영업활동현흐.9
495 영업활동현흐.10
496 영업활동현흐.11
497 영업활동현흐.12
498 영업활동현흐.13
499 영업활동현흐.14
500 영업활동현흐.15
501 영업활동현흐.16
502 영업활동현흐.17
503 영업활동현흐.18
504 영업활동현흐.19
505 영업활동현흐.20
506 영업활동현흐.21
507 영업활동현흐.22
508 영업활동현흐.23
509 영업활동현흐.24
510 영업활동현흐.25
511 영업활동현흐.26
512 영업활동현흐.27
513 영업활동현흐.28
514 영업활동현흐.29
515 영업활동현흐.30
516 영업활동현흐.31
517 영업활동현흐.32
518 영업활동현흐.33
519 영업활동현흐.34
520 영업활동현흐.35
521 영업활동현흐.36
522 영업활동현흐.37
523 영업활동현흐.38
524 매출총이익율
525 매출총이익율.1
526 매출총이익율.2
527 매출총이익율.3
528 매출총이익율.4
529 매출총이익율.5
530 매출총이익율.6
531 매출총이익율.7
532 매출총이익율.8
533 매출총이익율.9
534 매출총이익율.10
535 매출총이익율.11
536 매출총이익율.12
537 매출총이익율.13
538 매출총이익율.14
539 매출총이익율.15
540 매출총이익율.16
541 매출총이익율.17
542 매출총이익율.18
543 매출총이익율.19
544 매출총이익율.20
545 매출총이익율.21
546 매출총이익율.22
547 매출총이익율.23
548 매출총이익율.24
549 매출총이익율.25
550 매출총이익율.26
551 매출총이익율.27
552 매출총이익율.28
553 매출총이익율.29
554 매출총이익율.30
555 매출총이익율.31
556 매출총이익율.32
557 매출총이익율.33
558 매출총이익율.34
559 매출총이익율.35
560 매출총이익율.36
561 매출총이익율.37
562 매출총이익율.38
563 매출
564 매출.1
565 매출.2
566 매출.3
567 매출.4
568 매출.5
569 매출.6
570 매출.7
571 매출.8
572 매출.9
573 매출.10
574 매출.11
575 매출.12
576 매출.13
577 매출.14
578 매출.15
579 매출.16
580 매출.17
581 매출.18
582 매출.19
583 매출.20
584 매출.21
585 매출.22
586 매출.23
587 매출.24
588 매출.25
589 매출.26
590 매출.27
591 매출.28
592 매출.29
593 매출.30
594 매출.31
595 매출.32
596 매출.33
597 매출.34
598 매출.35
599 매출.36
600 매출.37
601 매출.38
602 매출.39
603 총자산
604 총자산.1
605 총자산.2
606 총자산.3
607 총자산.4
608 총자산.5
609 총자산.6
610 총자산.7
611 총자산.8
612 DPS
613 DPS.1
614 DPS.2
615 DPS.3
616 DPS.4
617 DPS.5
618 DPS.6
619 DPS.7
620 DPS.8
621 DPS.9
622 DPS.10
623 DPS.11
624 DPS.12
625 DPS.13
626 DPS.14
627 DPS.15
628 DPS.16
629 DPS.17
630 DPS.18
631 DPS.19
632 DPS.20
633 DPS.21
634 DPS.22
635 DPS.23
636 DPS.24
637 DPS.25
638 DPS.26
639 DPS.27
640 DPS.28
641 DPS.29
642 DPS.30
643 DPS.31
644 DPS.32
645 DPS.33
646 DPS.34
647 DPS.35
648 DPS.36
649 DPS.37
650 DPS.38

        Symbol Name   ROA                                                \
        Symbol Name 08/4Q 09/1Q 09/2Q 09/3Q  09/4Q  10/1Q  10/2Q  10/3Q
Symbol
A005930        삼성전자  7.62  5.24  3.78  5.46   6.93   8.74  10.53  11.46
A000660      SK하이닉스     0     0     0     0      0  12.57  18.73  25.35
A068270        셀트리온  2.92  4.89  8.63   7.3  10.48  11.75  14.02  17.22
A207940    삼성바이오로직스     0     0     0     0      0      0      0      0
A005380         현대차   4.5  3.94  4.67   6.6   8.36  10.01     10   9.82
...             ...   ...   ...   ...   ...    ...    ...    ...    ...
A297570   IBKS제9호스팩     0     0     0     0      0      0      0      0
A279410   한화에이스스팩4호     0     0     0     0      0      0      0      0
A258790   케이비제11호스팩     0     0     0     0      0      0      0      0
A264290   한화에이스스팩3호     0     0     0     0      0      0      0      0
A010400     우진아이엔에스     0     0     0     0      0      0      0      0

                ...    DPS                                                   \
         10/4Q  ...  16/1Q  16/2Q  16/3Q  16/4Q  17/1Q  17/2Q  17/3Q  17/4Q
Symbol          ...
A005930   12.1  ...    570    570    570    570    850    850    850    850
A000660  17.41  ...    600    600    600    600   1000   1000   1000   1000
A068270   9.68  ...  46.73  46.73  46.73  46.73  19.61  19.61  19.61  19.61
A207940      0  ...      0      0      0      0      0      0      0      0
A005380   7.82  ...   4000   4000   4000   4000   4000   4000   4000   4000
...        ...  ...    ...    ...    ...    ...    ...    ...    ...    ...
A297570      0  ...      0      0      0      0      0      0      0      0
A279410      0  ...      0      0      0      0      0      0      0      0
A258790      0  ...      0      0      0      0      0      0      0      0
A264290      0  ...      0      0      0      0      0      0      0      0
A010400      0  ...      0      0      0      0      0      0      0      0


         18/1Q  18/2Q
Symbol
A005930    850    850
A000660   1000   1000
A068270  19.61  19.61
A207940      0      0
A005380   4000   4000
...        ...    ...
A297570      0      0
A279410      0      0
A258790      0      0
A264290      0      0
A010400      0      0

[2053 rows x 650 columns]

In [71]:
price_raw = pd.read_csv('data_files/수정주가.csv', encoding='euckr')

In [74]:
price_df = price_raw.drop(0)

In [76]:
price_df.index = pd.to_datetime(price_df['코드명'])
price_df.drop(['코드명'], axis=1, inplace=True)

In [77]:
price_df

,A000010,A000020,A000030,A000040,A000050,A000060,A000070,A000080,A000090,A000100,...,A900340,A950010,A950030,A950070,A950100,A950110,A950130,A950140,A950160,A950170
코드명,,,,,,,,,,,,,,,,,,,,,
2006-01-31,NaN,3430,NaN,2317,12164,5788,57432,NaN,NaN,120947,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-02-28,NaN,3440,NaN,2279,9693,5015,55082,NaN,NaN,120947,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-03-31,NaN,3080,NaN,2039,10187,4775,58556,NaN,NaN,111188,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-04-28,NaN,5040,NaN,1918,10985,6060,62133,NaN,NaN,108050,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-05-30,NaN,5500,NaN,1332,10643,6008,57432,NaN,NaN,101079,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-10-31,NaN,9050,15750,558,11850,18200,86300,15750,NaN,160283,...,NaN,NaN,NaN,NaN,NaN,7150,3985,5610,34000,6570
2018-11-30,NaN,9110,15650,512,11250,21200,87500,17500,NaN,217698,...,2340,NaN,NaN,NaN,NaN,15300,4150,7290,41900,8200
2018-12-28,NaN,9100,15600,500,10800,21850,78500,16600,NaN,204500,...,1395,NaN,NaN,NaN,NaN,16300,4285,6230,43150,6730
2019-01-31,NaN,9840,14800,528,11000,22200,83200,16900,NaN,238000,...,1535,NaN,NaN,NaN,NaN,14200,4015,5490,39200,7120
2019-02-28,NaN,9800,NaN,507,11250,22100,84300,17700,NaN,260500,...,2290,NaN,NaN,NaN,NaN,12600,3980,5490,40300,8710

In [82]:
def price_data_preprocs(path):
    price_raw = pd.read_csv(path, encoding='euckr')
    price_df = price_raw.drop(0)
    price_df.index = pd.to_datetime(price_df['코드명'])
    del price_df['코드명']
    return price_df

In [83]:
price_data_preprocs('data_files/수정주가.csv')

,A000010,A000020,A000030,A000040,A000050,A000060,A000070,A000080,A000090,A000100,...,A900340,A950010,A950030,A950070,A950100,A950110,A950130,A950140,A950160,A950170
코드명,,,,,,,,,,,,,,,,,,,,,
2006-01-31,NaN,3430,NaN,2317,12164,5788,57432,NaN,NaN,120947,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-02-28,NaN,3440,NaN,2279,9693,5015,55082,NaN,NaN,120947,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-03-31,NaN,3080,NaN,2039,10187,4775,58556,NaN,NaN,111188,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-04-28,NaN,5040,NaN,1918,10985,6060,62133,NaN,NaN,108050,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-05-30,NaN,5500,NaN,1332,10643,6008,57432,NaN,NaN,101079,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-10-31,NaN,9050,15750,558,11850,18200,86300,15750,NaN,160283,...,NaN,NaN,NaN,NaN,NaN,7150,3985,5610,34000,6570
2018-11-30,NaN,9110,15650,512,11250,21200,87500,17500,NaN,217698,...,2340,NaN,NaN,NaN,NaN,15300,4150,7290,41900,8200
2018-12-28,NaN,9100,15600,500,10800,21850,78500,16600,NaN,204500,...,1395,NaN,NaN,NaN,NaN,16300,4285,6230,43150,6730
2019-01-31,NaN,9840,14800,528,11000,22200,83200,16900,NaN,238000,...,1535,NaN,NaN,NaN,NaN,14200,4015,5490,39200,7120
2019-02-28,NaN,9800,NaN,507,11250,22100,84300,17700,NaN,260500,...,2290,NaN,NaN,NaN,NaN,12600,3980,5490,40300,8710

In [117]:
data_df = finance_data_preprocessing('data_files/재무데이터 수정.xlsx')

In [122]:
data_df.columns

MultiIndex([('Symbol Name', 'Symbol Name'),
            (        'ROA',       '08/4Q'),
            (        'ROA',       '09/1Q'),
            (        'ROA',       '09/2Q'),
            (        'ROA',       '09/3Q'),
            (        'ROA',       '09/4Q'),
            (        'ROA',       '10/1Q'),
            (        'ROA',       '10/2Q'),
            (        'ROA',       '10/3Q'),
            (        'ROA',       '10/4Q'),
            ...
            (        'DPS',       '16/1Q'),
            (        'DPS',       '16/2Q'),
            (        'DPS',       '16/3Q'),
            (        'DPS',       '16/4Q'),
            (        'DPS',       '17/1Q'),
            (        'DPS',       '17/2Q'),
            (        'DPS',       '17/3Q'),
            (        'DPS',       '17/4Q'),
            (        'DPS',       '18/1Q'),
            (        'DPS',       '18/2Q')],
           length=650)

In [149]:
date = '17/4Q'
fin_df = data_df[[('시총', date), ('PER', date), ('PBR', date), ('PSR', date), ('Symbol Name', 'Symbol Name')]]

In [151]:
fin_df1 = fin_df[fin_df['시총'][date] > 0]

In [152]:
fin_df2 = fin_df1[(fin_df1['PER'][date] > 0) & (fin_df['PER'][date] < 10)]
fin_df3 = fin_df2[(fin_df2['PBR'][date] > 0) & (fin_df['PER'][date] < 1)]
fin_df4 = fin_df3[fin_df3['PSR'][date] > 0]

C:\Users\bitcamp\anaconda3\envs\py37_env\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.
C:\Users\bitcamp\anaconda3\envs\py37_env\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

In [128]:
def LSV(finance_df, date):
    data_df = finance_data_preprocessing('date_files/재무데이터 수정.xlsx')
    
    date = '17/4Q'
    fin_df = data_df[[('ROA', date), ('Symbol Name', 'Symbol Name')]]
    
    temp_df = data_df[[('ROA', date), ('Symbol Name', 'Symbol Name')]]
    temp_df = temp_df['ROA']['17/4Q'].sort_values(ascending=False)
    
    return temp_df

In [124]:
temp_df = data_df[[('ROA', date), ('Symbol Name', 'Symbol Name')]]

In [154]:
def small_size(path, date):
    data_df = finance_data_preprocessing(path)
    
    fin_df = data_df[[('시총', date), ('PER', date), ('PBR', date), ('PSR', date), ('Symbol Name', 'Symbol Name')]]
    fin_df['시총'][date] = pd.to_numeric(fin_df['시총'][date])
    
    market_cap_quantile_serices = fin_df['시총'][date].quantile(0.2)

In [160]:
path = 'data_files/재무데이터 수정.xlsx'
date = '17/4Q'

In [172]:
df = finance_data_preprocessing(path)

In [173]:
df

        Symbol Name   ROA                                                \
        Symbol Name 08/4Q 09/1Q 09/2Q 09/3Q  09/4Q  10/1Q  10/2Q  10/3Q
Symbol
A005930        삼성전자  7.62  5.24  3.78  5.46   6.93   8.74  10.53  11.46
A000660      SK하이닉스     0     0     0     0      0  12.57  18.73  25.35
A068270        셀트리온  2.92  4.89  8.63   7.3  10.48  11.75  14.02  17.22
A207940    삼성바이오로직스     0     0     0     0      0      0      0      0
A005380         현대차   4.5  3.94  4.67   6.6   8.36  10.01     10   9.82
...             ...   ...   ...   ...   ...    ...    ...    ...    ...
A297570   IBKS제9호스팩     0     0     0     0      0      0      0      0
A279410   한화에이스스팩4호     0     0     0     0      0      0      0      0
A258790   케이비제11호스팩     0     0     0     0      0      0      0      0
A264290   한화에이스스팩3호     0     0     0     0      0      0      0      0
A010400     우진아이엔에스     0     0     0     0      0      0      0      0

                ...    DPS                                                   \
         10/4Q  ...  16/1Q  16/2Q  16/3Q  16/4Q  17/1Q  17/2Q  17/3Q  17/4Q
Symbol          ...
A005930   12.1  ...    570    570    570    570    850    850    850    850
A000660  17.41  ...    600    600    600    600   1000   1000   1000   1000
A068270   9.68  ...  46.73  46.73  46.73  46.73  19.61  19.61  19.61  19.61
A207940      0  ...      0      0      0      0      0      0      0      0
A005380   7.82  ...   4000   4000   4000   4000   4000   4000   4000   4000
...        ...  ...    ...    ...    ...    ...    ...    ...    ...    ...
A297570      0  ...      0      0      0      0      0      0      0      0
A279410      0  ...      0      0      0      0      0      0      0      0
A258790      0  ...      0      0      0      0      0      0      0      0
A264290      0  ...      0      0      0      0      0      0      0      0
A010400      0  ...      0      0      0      0      0      0      0      0


         18/1Q  18/2Q
Symbol
A005930    850    850
A000660   1000   1000
A068270  19.61  19.61
A207940      0      0
A005380   4000   4000
...        ...    ...
A297570      0      0
A279410      0      0
A258790      0      0
A264290      0      0
A010400      0      0

[2053 rows x 650 columns]

In [180]:
def benjamin_grahm(paht, date):
    data_df = finance_data_preprocessing(path)
    
    fin_df = data_df[[('시총', date), ('ROA', date), ('부채비율', date), ('PBR', date), ('Symbol Name', 'Symbol Name')]]
    fin_df['시총'][date] = pd.to_numeric(fin_df['시총'][date])
    
  
    filtered_df = fin_df[fin_df['ROA'][date] >= 0.05]
    filtered_df = filtered_df[filtered_df['부채비율'][date] <= 100]
    filtered_df = filtered_df[filtered_df['PBR'][date] >= 0.2]
    filtered_df = filtered_df['PBR'][date].sort_values()[:10]
    
    return filtered_df

In [181]:
benjamin_grahm(path, date)

C:\Users\bitcamp\anaconda3\envs\py37_env\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

Symbol
A002300    0.22
A900110    0.26
A900080    0.28
A005010    0.28
A012320    0.29
A101930    0.29
A024830     0.3
A004360    0.31
A003830    0.32
A006200    0.32
Name: 17/4Q, dtype: object

In [ ]:
start_date = '2015-1'
init_money = 1000
restfree_rete
backtext_price =

In [182]:
# 5개의 종목 균등 비율 pfo

In [183]:
selected_list = ['A000020', 'A000030', 'A000040', 'A000050', 'A000060']

In [184]:
backtext_price[select_list]

NameError: name 'backtext_price' is not defined

In [ ]:
each_money = init_money/len(select_list)

In [ ]:
pf_values = 0
for code in selected_list:
    temp_num = int(each_money/int(backtest_price.iloc[0][code]))
    pf_value = pf_value + pd.to_numeric(backtest _price[code]) * temp_num

In [ ]:
cash = init_money - pf.value[0]
cash_pf = []

for i in range(0, len(pf_value)):
    cash_pf.append(cash * (1 + riskfree_rate/12) ** i)

In [ ]:
becktest_df = pd.DateFrame({'주석포트': pf_value})